### ISSUE TITLE
Commenting is broken

### ISSUE THREAD

**Issue by pulkitkrishna00** [NickvisionApps/nickvisionapps.github.io#4]
The commenting system for this site is broken:
![image](https://github.com/NickvisionApps/nickvisionapps.github.io/assets/72264063/40c9e042-a15d-46f9-84d5-012c8e3012d9)

**Comment by nlogozzo** [comment]
Should be fixed.  Try again.

**Comment by nlogozzo** [comment]
You can also comment on issue #3 and it will show on the article.
